language: node_js
node_js: stable
# S: Build Lifecycle
install:
- npm install
before_install:
- git submodule update --init --remote --recursive
#before_script:
# - npm install -g gulp
script:
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "Michael"
- git config user.email "jing2si@gmail.com"
- git add .
- git commit -m "site update"
- git push --force --quiet "https://${github_token}@${GH_REF}" master:master
# E: Build LifeCycle
branches:
only:
- Source
env:
global:
- GH_REF: github.com/jing2si/jing2si.github.io.git